# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: OpenCube Documentation
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.copy
    - content.code.select
  palette:
    scheme: slate
    primary: green
    accent: light green
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

